export const data = [
  {
    key: "1",
    firstName: "John",
    lastName: "Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
    tags: ["nice", "developer"],
  },
  {
    key: "2",
    firstName: "Jim",
    lastName: "Green",
    age: 42,
    address: "London No. 1 Lake Park",
    tags: ["loser"],
  },
  {
    key: "3",
    firstName: "Joe",
    lastName: "Black",
    age: 32,
    address: "Sydney No. 1 Lake Park",
    tags: ["cool", "teacher"],
  },
  {
    key: "4",
    firstName: "Anna",
    lastName: "Smith",
    age: 25,
    address: "Paris No. 2 River Road",
    tags: ["friendly", "designer"],
  },
  {
    key: "5",
    firstName: "Tom",
    lastName: "Johnson",
    age: 29,
    address: "Berlin No. 3 Tree Avenue",
    tags: ["creative", "developer"],
  },
  {
    key: "6",
    firstName: "Emma",
    lastName: "Williams",
    age: 35,
    address: "Tokyo No. 4 Lake View",
    tags: ["leader", "manager"],
  },
  {
    key: "7",
    firstName: "Liam",
    lastName: "Davis",
    age: 27,
    address: "Moscow No. 5 Hill Top",
    tags: ["hardworking", "intern"],
  },
  {
    key: "8",
    firstName: "Sophia",
    lastName: "Taylor",
    age: 24,
    address: "Delhi No. 6 Garden Street",
    tags: ["enthusiastic", "writer"],
  },
  {
    key: "9",
    firstName: "William",
    lastName: "Anderson",
    age: 40,
    address: "Beijing No. 7 Bamboo Road",
    tags: ["organized", "teacher"],
  },
  {
    key: "10",
    firstName: "Isabella",
    lastName: "Thomas",
    age: 31,
    address: "Seoul No. 8 Mountain Path",
    tags: ["motivated", "artist"],
  },
  {
    key: "11",
    firstName: "James",
    lastName: "Martinez",
    age: 28,
    address: "Rome No. 9 Piazza",
    tags: ["funny", "photographer"],
  },
  {
    key: "12",
    firstName: "Mia",
    lastName: "Hernandez",
    age: 36,
    address: "Bangkok No. 10 Sunset Lane",
    tags: ["kind", "doctor"],
  },
  {
    key: "13",
    firstName: "Ethan",
    lastName: "Lopez",
    age: 33,
    address: "Dubai No. 11 City Center",
    tags: ["ambitious", "engineer"],
  },
  {
    key: "14",
    firstName: "Olivia",
    lastName: "Gonzalez",
    age: 30,
    address: "Toronto No. 12 Parkside",
    tags: ["energetic", "nurse"],
  },
  {
    key: "15",
    firstName: "Lucas",
    lastName: "Wilson",
    age: 26,
    address: "Miami No. 13 Ocean Drive",
    tags: ["focused", "student"],
  },
  {
    key: "16",
    firstName: "Charlotte",
    lastName: "Clark",
    age: 29,
    address: "Madrid No. 14 Sunny Square",
    tags: ["perfectionist", "chef"],
  },
  {
    key: "17",
    firstName: "Henry",
    lastName: "Hall",
    age: 37,
    address: "Amsterdam No. 15 Flower Lane",
    tags: ["dedicated", "scientist"],
  },
  {
    key: "18",
    firstName: "Ava",
    lastName: "Allen",
    age: 23,
    address: "Vienna No. 16 Classic Street",
    tags: ["cheerful", "musician"],
  },
  {
    key: "19",
    firstName: "Benjamin",
    lastName: "Young",
    age: 34,
    address: "Sydney No. 17 Coastal Road",
    tags: ["honest", "teacher"],
  },
  {
    key: "20",
    firstName: "Ella",
    lastName: "King",
    age: 27,
    address: "Osaka No. 18 Market Alley",
    tags: ["calm", "accountant"],
  },
  {
    key: "21",
    firstName: "Alexander",
    lastName: "Wright",
    age: 38,
    address: "San Francisco No. 19 Bay Area",
    tags: ["confident", "entrepreneur"],
  },
  {
    key: "22",
    firstName: "Grace",
    lastName: "Scott",
    age: 32,
    address: "Lisbon No. 20 Riverfront",
    tags: ["adventurous", "traveler"],
  },
  {
    key: "23",
    firstName: "Daniel",
    lastName: "Adams",
    age: 39,
    address: "Zurich No. 21 Snow Street",
    tags: ["efficient", "banker"],
  },
  {
    key: "24",
    firstName: "Chloe",
    lastName: "Baker",
    age: 28,
    address: "Athens No. 22 Historic District",
    tags: ["innovative", "architect"],
  },
  {
    key: "25",
    firstName: "Matthew",
    lastName: "Nelson",
    age: 35,
    address: "Helsinki No. 23 Modern Square",
    tags: ["logical", "analyst"],
  },
  {
    key: "26",
    firstName: "Scarlett",
    lastName: "Carter",
    age: 25,
    address: "Prague No. 24 Old Town",
    tags: ["brave", "filmmaker"],
  },
  {
    key: "27",
    firstName: "Jackson",
    lastName: "Mitchell",
    age: 41,
    address: "Berlin No. 25 Unity Lane",
    tags: ["experienced", "consultant"],
  },
  {
    key: "28",
    firstName: "Lily",
    lastName: "Perez",
    age: 26,
    address: "Kuala Lumpur No. 26 Skyline Road",
    tags: ["passionate", "journalist"],
  },
  {
    key: "29",
    firstName: "David",
    lastName: "Roberts",
    age: 31,
    address: "Cape Town No. 27 Harbor View",
    tags: ["practical", "mechanic"],
  },
  {
    key: "30",
    firstName: "Zoe",
    lastName: "Turner",
    age: 22,
    address: "Reykjavik No. 28 Glacier Lane",
    tags: ["curious", "student"],
  },
  {
    key: "28",
    firstName: "Lily",
    lastName: "Perez",
    age: 26,
    address: "Kuala Lumpur No. 26 Skyline Road",
    tags: ["passionate", "journalist"],
  },
  {
    key: "29",
    firstName: "David",
    lastName: "Roberts",
    age: 31,
    address: "Cape Town No. 27 Harbor View",
    tags: ["practical", "mechanic"],
  },
  {
    key: "30",
    firstName: "Zoe",
    lastName: "Turner",
    age: 22,
    address: "Reykjavik No. 28 Glacier Lane",
    tags: ["curious", "student"],
  },
];
