export const data = [
  {
    key: "1",
    name: "John Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  { key: "2", name: "Jim Green", age: 42, address: "London No. 1 Lake Park" },
  { key: "3", name: "Joe Black", age: 32, address: "Sydney No. 1 Lake Park" },
  { key: "4", name: "Jim Red", age: 32, address: "London No. 2 Lake Park" },
  { key: "5", name: "Alice Blue", age: 28, address: "Paris No. 1 Avenue" },
  { key: "6", name: "Bob Yellow", age: 35, address: "Berlin No. 3 Square" },
  { key: "7", name: "Charlie Purple", age: 22, address: "Tokyo No. 5 Street" },
  { key: "8", name: "Diana Orange", age: 40, address: "Rome No. 2 Piazza" },
  { key: "9", name: "Eva White", age: 30, address: "London No. 7 Boulevard" },
  { key: "10", name: "Frank Green", age: 38, address: "New York No. 8 Road" },
  { key: "11", name: "Grace Pink", age: 27, address: "Sydney No. 4 Park" },
  { key: "12", name: "Hank Brown", age: 45, address: "Paris No. 6 Alley" },
  { key: "13", name: "Ivy Red", age: 33, address: "Berlin No. 9 Lane" },
  { key: "14", name: "Jack Black", age: 29, address: "Rome No. 3 Square" },
  { key: "15", name: "Lily Blue", age: 36, address: "London No. 2 Court" },
  { key: "16", name: "Mason Green", age: 31, address: "Tokyo No. 6 District" },
  { key: "17", name: "Nina White", age: 28, address: "New York No. 5 Road" },
  { key: "18", name: "Oscar Yellow", age: 34, address: "Paris No. 8 Lane" },
  { key: "19", name: "Paul Pink", age: 41, address: "Berlin No. 10 Circle" },
  { key: "20", name: "Quincy Orange", age: 27, address: "Rome No. 4 Place" },
  { key: "21", name: "Rita Blue", age: 39, address: "Sydney No. 3 Street" },
  {
    key: "22",
    name: "Sam Brown",
    age: 25,
    address: "New York No. 2 Boulevard",
  },
  { key: "23", name: "Tina Green", age: 32, address: "Tokyo No. 1 Park" },
  { key: "24", name: "Ursula White", age: 40, address: "London No. 9 Avenue" },
];
